import argon2 from 'argon2';
import { Pool } from 'pg';
import { z } from 'zod';
import { SafeUser } from './auth.js';
const pool=new Pool({connectionString:process.env.DATABASE_URL});
export const profileSchema=z.object({email:z.email(),firstName:z.string().trim().min(1),lastName:z.string().trim().min(1),street:z.string().trim().max(160).optional(),houseNumber:z.string().trim().max(32).optional(),postalCode:z.string().trim().max(16).optional(),city:z.string().trim().max(120).optional(),phoneNumber:z.string().trim().max(48).optional(),mobileNumber:z.string().trim().max(48).optional()});
export const passwordSchema=z.object({currentPassword:z.string().min(1),newPassword:z.string().min(12)});
export const deleteAccountSchema=z.object({confirmed:z.literal(true)});
export async function profile(user:SafeUser){const r=await pool.query('SELECT u.email,u.first_name AS "firstName",u.last_name AS "lastName",p.street,p.house_number AS "houseNumber",p.postal_code AS "postalCode",p.city,p.phone_number AS "phoneNumber",p.mobile_number AS "mobileNumber" FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id WHERE u.id=$1',[user.id]);return r.rows[0]}
export async function updateProfile(user:SafeUser,input:z.infer<typeof profileSchema>){try{await pool.query('BEGIN');await pool.query('UPDATE users SET email=$1,first_name=$2,last_name=$3,updated_at=now() WHERE id=$4',[input.email.trim().toLowerCase(),input.firstName,input.lastName,user.id]);await pool.query('INSERT INTO user_profiles(user_id,street,house_number,postal_code,city,phone_number,mobile_number,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(user_id) DO UPDATE SET street=excluded.street,house_number=excluded.house_number,postal_code=excluded.postal_code,city=excluded.city,phone_number=excluded.phone_number,mobile_number=excluded.mobile_number,updated_at=now()',[user.id,input.street||null,input.houseNumber||null,input.postalCode||null,input.city||null,input.phoneNumber||null,input.mobileNumber||null]);await pool.query('COMMIT');return profile(user)}catch(e){await pool.query('ROLLBACK');if((e as {code?:string}).code==='23505')throw new Error('EMAIL_EXISTS');throw e}}
export async function deleteAccount(user:SafeUser){const schools=(await pool.query<{id:string}>('SELECT sm.school_id AS id FROM school_memberships sm WHERE sm.user_id=$1 AND NOT EXISTS (SELECT 1 FROM school_memberships other WHERE other.school_id=sm.school_id AND other.user_id<>$1)',[user.id])).rows.map(r=>r.id);const all=(await pool.query<{id:string}>('SELECT school_id AS id FROM school_memberships WHERE user_id=$1',[user.id])).rows.map(r=>r.id);if(schools.length!==all.length)throw new Error('ACCOUNT_HAS_SHARED_SCHOOLS');const blobs=(await pool.query<{blobName:string}>('SELECT d.blob_name AS "blobName" FROM measure_documents d JOIN measures m ON m.id=d.measure_id WHERE m.school_id=ANY($1)',[schools])).rows;const {BlobServiceClient}=await import('@azure/storage-blob');const {DefaultAzureCredential}=await import('@azure/identity');const url=process.env.AZURE_STORAGE_ACCOUNT_URL;if(!url)throw new Error('DOCUMENT_STORAGE_UNAVAILABLE');const container=new BlobServiceClient(url,new DefaultAzureCredential()).getContainerClient('digitalpakt');for(const blob of blobs)await container.getBlockBlobClient(blob.blobName).deleteIfExists();await pool.query('BEGIN');try{if(schools.length)await pool.query('DELETE FROM schools WHERE id=ANY($1)',[schools]);await pool.query('DELETE FROM users WHERE id=$1',[user.id]);await pool.query('COMMIT')}catch(e){await pool.query('ROLLBACK');throw e}}
export async function changePassword(user:SafeUser,input:z.infer<typeof passwordSchema>){const r=await pool.query<{passwordHash:string}>('SELECT password_hash AS "passwordHash" FROM users WHERE id=$1',[user.id]);if(!r.rows[0]||!await argon2.verify(r.rows[0].passwordHash,input.currentPassword))throw new Error('INVALID_CREDENTIALS');await pool.query('UPDATE users SET password_hash=$1,updated_at=now() WHERE id=$2',[await argon2.hash(input.newPassword,{type:argon2.argon2id}),user.id])}
