import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';

type Editable = { name:string|null; description:string|null; affectedAreaSqm:number|null; studentCount:number|null; teacherCount:number|null; existingEquipment:string|null; previousDigitalisationMeasures:string|null; receivedFunding:string|null; implementationStartDate:string|null; implementationEndDate:string|null; estimatedCostEur:number|null; implementationStatus:'planned'|'started'|'completed'|null; fundingArea:'infrastructure_network_wlan'|'digital_devices'|'educational_software_platforms'|null };
type Measure = Editable & { id:string; schoolId:string; updatedAt:string };
const empty: Editable = { name:null, description:null, affectedAreaSqm:null, studentCount:null, teacherCount:null, existingEquipment:null, previousDigitalisationMeasures:null, receivedFunding:null, implementationStartDate:null, implementationEndDate:null, estimatedCostEur:null, implementationStatus:null, fundingArea:null };
const areas = [['infrastructure_network_wlan', 'IT-Infrastruktur, Netzwerk und WLAN'], ['digital_devices', 'Digitale Endgeräte'], ['educational_software_platforms', 'Bildungssoftware und digitale Lernplattformen']] as const;

export function MeasurePage({ measureId }: { measureId?: string }) {
  const navigate = useNavigate(); const [measure, setMeasure] = useState<Measure|Editable>(empty); const [state, setState] = useState<'loading'|'idle'|'saving'|'saved'|'error'>('idle'); const [error, setError] = useState(''); const timer = useRef<number|undefined>(undefined);
  useEffect(() => { if (!measureId) return; setState('loading'); void (async () => { try { const response = await fetch(`/api/measures/${measureId}`, { credentials:'same-origin' }); if (!response.ok) throw new Error(); setMeasure((await response.json()).measure); setState('saved'); } catch { setState('error'); setError('Die Maßnahme konnte nicht geladen werden.'); } })(); return () => window.clearTimeout(timer.current); }, [measureId]);
  const persisted = (value: Measure|Editable): value is Measure => 'id' in value;
  function autosave(next: Measure) { window.clearTimeout(timer.current); setState('saving'); timer.current = window.setTimeout(async () => { try { const { id, schoolId: _schoolId, updatedAt: _updatedAt, ...payload } = next; const response = await fetch(`/api/measures/${id}`, { method:'PATCH', credentials:'same-origin', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); if (!response.ok) throw new Error(); setMeasure((await response.json()).measure); setState('saved'); } catch { setState('error'); setError('Speichern nicht möglich. Bitte versuchen Sie es erneut.'); } }, 500); }
  function change(event: ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>) { const { name, value, type } = event.currentTarget; if (type === 'number' && value !== '') { const numeric = Number(value.replace(',', '.')); if (!Number.isFinite(numeric)) { setError('Bitte geben Sie eine gültige Zahl ein.'); setState('error'); return; } const next = { ...measure, [name]: numeric } as Measure|Editable; setMeasure(next); if (persisted(next)) autosave(next); return; } const next = { ...measure, [name]: type === 'number' ? null : (value || null) } as Measure|Editable; setMeasure(next); if (persisted(next)) autosave(next); }
  async function submit(event: FormEvent) { event.preventDefault(); if (persisted(measure)) return; if (!measure.name?.trim()) { setError('Bitte geben Sie eine Bezeichnung für die Maßnahme an.'); return; } setState('saving'); setError(''); try { const response = await fetch('/api/measures', { method:'POST', credentials:'same-origin', headers:{'Content-Type':'application/json'}, body:JSON.stringify(measure) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message); setMeasure(body.measure); setState('saved'); navigate(`/app/measures/${body.measure.id}`, { replace:true }); } catch (reason) { setState('error'); setError(reason instanceof Error && reason.message ? reason.message : 'Die Maßnahme konnte nicht angelegt werden.'); } }
  if (state === 'loading') return <p className="app-loading">Maßnahme wird geladen …</p>;
  const created = persisted(measure);
  return <section className="app-panel school-page" aria-labelledby="measure-title"><p className="eyebrow">Nächster Arbeitsschritt</p><h1 id="measure-title" lang="de">Digitalisierungs­maßnahme erfassen</h1><p>Die Erfassung einer Maßnahme ist keine Aussage zur Antragsberechtigung Ihrer Schule.</p>{created && <p className={`save-status ${state}`} role="status">{state === 'saving' ? 'Speichert …' : state === 'saved' ? 'Alle Änderungen gespeichert.' : ''}</p>}{error && <p className="form-error" role="alert">{error}</p>}
    <form className="school-form" onSubmit={submit}>
      <label>Bezeichnung der Maßnahme <strong aria-hidden="true">*</strong><input name="name" value={measure.name ?? ''} onChange={change} required maxLength={200} placeholder="z. B. WLAN-Ausbau" /></label>
      <label>Kurzbeschreibung<textarea name="description" value={measure.description ?? ''} onChange={change} maxLength={4000} /></label>
      <label>Schulfläche / betroffene Fläche in m²<input name="affectedAreaSqm" type="number" min="0" step="0.01" value={measure.affectedAreaSqm ?? ''} onChange={change} /></label><label>Anzahl der Schülerinnen und Schüler<input name="studentCount" type="number" min="0" step="1" value={measure.studentCount ?? ''} onChange={change} /></label><label>Anzahl der Lehrkräfte<input name="teacherCount" type="number" min="0" step="1" value={measure.teacherCount ?? ''} onChange={change} /></label>
      <label>Vorhandene technische Ausstattung<textarea name="existingEquipment" value={measure.existingEquipment ?? ''} onChange={change} maxLength={4000} /></label><label>Frühere Digitalisierungsmaßnahmen<textarea name="previousDigitalisationMeasures" value={measure.previousDigitalisationMeasures ?? ''} onChange={change} maxLength={4000} /></label><label>Bereits erhaltene Fördermittel<textarea name="receivedFunding" value={measure.receivedFunding ?? ''} onChange={change} maxLength={4000} /></label>
      <fieldset className="implementation-date-range"><legend>Umsetzungszeitraum</legend><label>Beginn der Umsetzung<input name="implementationStartDate" type="date" value={measure.implementationStartDate ?? ''} onChange={change} /></label><label>Ende der Umsetzung<input name="implementationEndDate" type="date" min={measure.implementationStartDate ?? undefined} value={measure.implementationEndDate ?? ''} onChange={change} /></label></fieldset>
      <label>Voraussichtliche Kosten in EUR<input name="estimatedCostEur" type="number" min="0" step="0.01" value={measure.estimatedCostEur ?? ''} onChange={change} /></label><label>Umsetzungsstatus<select name="implementationStatus" value={measure.implementationStatus ?? ''} onChange={change}><option value="">Bitte auswählen</option><option value="planned">Geplant</option><option value="started">Begonnen</option><option value="completed">Abgeschlossen</option></select></label>
      <fieldset><legend>Förderbereich</legend>{areas.map(([value,label]) => <label key={value}><input type="radio" name="fundingArea" value={value} checked={measure.fundingArea === value} onChange={change} /> {label}</label>)}</fieldset>
      {!created && <button className="primary-button" type="submit" disabled={state === 'saving'}>{state === 'saving' ? 'Maßnahme wird angelegt …' : 'Als Maßnahme anlegen'}</button>}
    </form><section className="eligibility-panel"><h2>Förderbereich im MVP</h2><p>Pro Maßnahme kann genau ein Förderbereich ausgewählt werden. Andere Förderbereiche liegen außerhalb des MVP und werden nicht bewertet.</p></section>
  </section>;
}
