import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';

type Item={id:string;name:string|null;fundingArea:string|null;implementationStatus:string|null;updatedAt:string;submittedAt:string|null;reviewReference:string|null;reviewStatus:string;reviewOpenedAt:string|null;publicMessage:string|null};
const areas:Record<string,string>={infrastructure_network_wlan:'IT-Infrastruktur, Netzwerk und WLAN',digital_devices:'Digitale Endgeräte',educational_software_platforms:'Bildungssoftware und digitale Lernplattformen'};
const statuses:Record<string,string>={planned:'Geplant',started:'Begonnen',completed:'Abgeschlossen'};

export function MeasuresPage(){
  const [items,setItems]=useState<Item[]|null>(null); const [ready,setReady]=useState<Record<string,boolean>>({}); const [notice,setNotice]=useState(''); const [commentFor,setCommentFor]=useState<Item|null>(null);
  useEffect(()=>{void fetch('/api/measures',{credentials:'same-origin'}).then(async r=>r.ok?(await r.json()).measures:[]).then(async(ms:Item[])=>{setItems(ms);const entries=await Promise.all(ms.map(async m=>{const [q,d]=await Promise.all([fetch(`/api/measures/${m.id}/questions`,{credentials:'same-origin'}).then(r=>r.json()),fetch(`/api/measures/${m.id}/documents`,{credentials:'same-origin'}).then(r=>r.json())]);return [m.id,(q.answers?.length===9&&d.documents?.length>0)] as const}));setReady(Object.fromEntries(entries))}).catch(()=>setItems([]))},[]);
  async function submit(id:string){const r=await fetch(`/api/measures/${id}/submit-review`,{method:'POST',credentials:'same-origin'});const data=await r.json().catch(()=>null);if(r.ok)setItems(current=>current?.map(item=>item.id===id?data.measure:item)??null);else setNotice(data?.error?.message??'Einreichung nicht möglich.');}
  if(!items)return <p className="app-loading">Maßnahmen werden geladen …</p>;
  return <section className="app-panel" aria-labelledby="measures-title"><p className="eyebrow">Meine Maßnahmen</p><h1 id="measures-title">Maßnahmenübersicht</h1>{notice&&<p className="form-error">{notice}</p>}<p><Link className="primary-button" to="/app/measures/new">Neue Maßnahme anlegen</Link></p>{items.length===0?<p>Noch keine Maßnahme angelegt.</p>:<ul className="measure-list">{items.map(item=>{const needsComment=item.reviewStatus==='NEEDS_CHANGES'||item.reviewStatus==='NOT_ELIGIBLE';return <li key={item.id}><h2>{item.name||'Unbenannte Maßnahme'}</h2><p>{areas[item.fundingArea??'']??'Förderbereich noch nicht gewählt'} · {statuses[item.implementationStatus??'']??'Status noch nicht gewählt'}</p>{item.submittedAt&&item.reviewStatus!=='NEEDS_CHANGES'?<p><strong>{item.reviewStatus==='ELIGIBLE'?'🟢 Grundsätzlich förderfähig':item.reviewStatus==='NOT_ELIGIBLE'?'🔴 Derzeit nicht förderfähig':item.reviewStatus==='UNDER_REVIEW'?'In Bearbeitung – Vorgang geöffnet':item.reviewStatus==='RESUBMITTED'?'Erneut eingereicht':'Zur Überprüfung gesendet'}</strong><br/>Bearbeitungsnummer: {item.reviewReference}{item.reviewOpenedAt&&<><br/>Zuletzt bearbeitet: {new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.reviewOpenedAt))}</>}</p>:<><p>{item.reviewStatus==='NEEDS_CHANGES'?<><strong>🟡 Nachbearbeitung erforderlich</strong><br/>Bitte ergänzen Sie die angeforderten Angaben und reichen Sie die Maßnahme erneut ein.</>:<>Zuletzt geändert: {new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(item.updatedAt))}</>}</p><div className="measure-actions"><Link className="secondary-button" to={`/app/measures/${item.id}`}>Öffnen und bearbeiten</Link>{needsComment&&<button className="secondary-button review-comment-button" type="button" onClick={()=>setCommentFor(item)}>Anmerkungen</button>}<button className="primary-button" disabled={!ready[item.id]} onClick={()=>void submit(item.id)}>{item.reviewStatus==='NEEDS_CHANGES'?'Erneut zur Prüfung einreichen':'Zur Überprüfung senden'}</button></div>{!ready[item.id]&&<p>Verfügbar nach neun beantworteten Fragen und mindestens einem Dokument.</p>}</>}{item.reviewStatus==='NOT_ELIGIBLE'&&<div className="measure-actions"><button className="secondary-button review-comment-button" type="button" onClick={()=>setCommentFor(item)}>Anmerkungen</button></div>}</li>})}</ul>}{commentFor&&<div className="review-comment-backdrop" role="presentation" onMouseDown={()=>setCommentFor(null)}><section className="review-comment-dialog" role="dialog" aria-modal="true" aria-labelledby="review-comment-title" onMouseDown={event=>event.stopPropagation()}><h2 id="review-comment-title">Anmerkungen der Sachbearbeitung</h2><p>{commentFor.publicMessage??'Für diese Entscheidung wurden keine Anmerkungen hinterlegt.'}</p><button className="primary-button" type="button" onClick={()=>setCommentFor(null)}>Schließen</button></section></div>}</section>;
}
